### ISSUE TITLE
App crashes when click image menu button

### ISSUE THREAD

**Issue by geniuslittleteddy** [tobykurien/WebApps#204]
Steps to reproduce
1. open github website
2. unblock 3rd party domains 
![pic1](https://user-images.githubusercontent.com/67744580/89712888-5e799600-d9c6-11ea-9d29-41cf6546fff6.png)
3. Sign up
![pic4](https://user-images.githubusercontent.com/67744580/89712895-6b968500-d9c6-11ea-87e2-efe279274a04.png)
4. Share URL
![pic7](https://user-images.githubusercontent.com/67744580/89712905-794c0a80-d9c6-11ea-9b38-d461ad4d23b7.png)
5. Click image menu button
![pic9](https://user-images.githubusercontent.com/67744580/89712911-80731880-d9c6-11ea-9648-4266897114d8.png)

```
07-29 07:46:03.559  4630  4630 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.tobykurien.webapps.utils.Settings.isLoadImages()' on a null object reference
07-29 07:46:03.559  4630  4630 E AndroidRuntime: 	at com.tobykurien.webapps.webviewclient.WebViewUtilsApi11.setupWebView(WebViewUtilsApi11.xtend)
07-29 07:46:03.559  4630  4630 E AndroidRuntime: 	at com.tobykurien.webapps.webviewclient.WebViewUtilsApi12.setupWebView(WebViewUtilsApi12.xtend)
07-29 07:46:03.559  4630  4630 E AndroidRuntime: 	at com.tobykurien.webapps.webviewclient.WebViewUtilsApi16.setupWebView(WebViewUtilsApi16.xtend)
07-29 07:46:03.559  4630  4630 E AndroidRuntime: 	at com.tobykurien.webapps.webviewclient.WebViewUtilsApi19.setupWebView(WebViewUtilsApi19.xtend)
07-29 07:46:03.559  4630  4630 E AndroidRuntime: 	at com.tobykurien.webapps.webviewclient.WebViewUtilsApi21.setupWebView(WebViewUtilsApi21.xtend)
07-29 07:46:03.559  4630  4630 E AndroidRuntime: 	at com.tobykurien.webapps.activity.BaseWebAppActivity.setupWebView(BaseWebAppActivity.xtend)
07-29 07:46:03.559  4630  4630 E AndroidRuntime: 	at com.tobykurien.webapps.activity.WebAppActivity.onOptionsItemSelected(WebAppActivity.xtend)
07-29 07:46:03.559  4630  4630 E AndroidRuntime: 	at android.app.Activity.onMenuItemSelected(Activity.java:3204)
07-29 07:46:03.559  4630  4630 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java)
07-29 07:46:03.559  4630  4630 E AndroidRuntime: 	at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java)
07-29 07:46:03.559  4630  4630 E AndroidRuntime: 	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java)
07-29 07:46:03.559  4630  4630 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV9.onMenuItemSelected(AppCompatDelegateImplV9.java)
07-29 07:46:03.559  4630  4630 E AndroidRuntime: 	at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java)
07-29 07:46:03.559  4630  4630 E AndroidRuntime: 	at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java)
07-29 07:46:03.559  4630  4630 E AndroidRuntime: 	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java)
07-29 07:46:03.559  4630  4630 E AndroidRuntime: 	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java)
07-29 07:46:03.559  4630  4630 E AndroidRuntime: 	at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java)
07-29 07:46:03.559  4630  4630 E AndroidRuntime: 	at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java)
07-29 07:46:03.559  4630  4630 E AndroidRuntime: 	at android.view.View.performClick(View.java:5609)
07-29 07:46:03.559  4630  4630 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:22262)
07-29 07:46:03.559  4630  4630 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
07-29 07:46:03.559  4630  4630 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-29 07:46:03.559  4630  4630 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
07-29 07:46:03.559  4630  4630 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6077)
07-29 07:46:03.559  4630  4630 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-29 07:46:03.559  4630  4630 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
07-29 07:46:03.559  4630  4630 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
07-29 07:46:03.560  1608   995 W ActivityManager:   Force finishing activity com.tobykurien.webapps/.activity.WebAppActivity
07-29 07:46:03.562  1608   995 W ActivityManager:   Force finishing activity com.tobykurien.webapps/.activity.WebAppActivity
```

**Comment by tobykurien** [comment]
should be fixed in latest release
