### ISSUE TITLE
Unblock 3rd Party Domains button error

### ISSUE THREAD

**Issue by raven9nine** [tobykurien/WebApps#89]
On pressing unblock third party domains button: Unfortunately WebApps has stopped.
WebApps v2.13
Android 4.4.2

**Comment by sm4rk0** [comment]
This is the stack trace:
```
AndroidRuntime: FATAL EXCEPTION: main
AndroidRuntime: Process: com.tobykurien.webapps, PID: 20137
AndroidRuntime: Theme: themes:{org.adw.launcher=overlay:org.cyanogenmod.hexolibre}
AndroidRuntime: java.lang.NoClassDefFoundError: com.tobykurien.webapps.activity.WebAppActivity$12$3
AndroidRuntime:        at com.tobykurien.webapps.activity.WebAppActivity$12.apply(WebAppActivity.java:623)
AndroidRuntime:        at com.tobykurien.webapps.activity.WebAppActivity$12.apply(WebAppActivity.java:603)
AndroidRuntime:        at org.xtendroid.utils.AsyncBuilder.onPostExecute(AsyncBuilder.xtend:86)
AndroidRuntime:        at android.os.AsyncTask.finish(AsyncTask.java:651)
AndroidRuntime:        at android.os.AsyncTask.-wrap1(AsyncTask.java)
AndroidRuntime:        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5461)
AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
AndroidRuntime:        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
ActivityManager:   Force finishing activity com.tobykurien.webapps/.activity.WebAppActivity
```

**Comment by tobykurien** [comment]
Thanks, will fix this soon
